# Generated by Django 4.2.1 on 2023-05-31 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scores", "0002_alter_user_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Plebs",
        ),
    ]
