# Generated by Django 4.2.1 on 2023-05-31 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scores", "0003_rename_user_plebs"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Plebs",
            new_name="Sirotinja",
        ),
    ]
