# Generated by Django 4.2.1 on 2023-05-31 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scores", "0004_rename_plebs_sirotinja"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Sirotinja",
            new_name="Peasant",
        ),
    ]
