# Generated by Django 4.2.1 on 2023-05-31 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "scores",
            "0006_peasant_password_peasant_username_alter_peasant_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="peasant",
            name="username",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
